# https://docs.spring.io/spring-boot/appendix/application-properties/index.html#appendix.application-properties.server
server:
  port: 8890
  tomcat:
    keep-alive-timeout: -1 # 無制限
    max-swallow-size: -1  # 無制限
    max-http-form-post-size: 32MB
    connection-timeout: 60s
    threads:
      min-spare: 2
      max: 20
    max-connections: 20
    accept-count: 20
  ssl:
    enabled: false

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.reactive.WebFluxAutoConfiguration #webFlex系 自前で全部構築しているのでいらない
      - org.springframework.boot.autoconfigure.web.reactive.function.client.WebClientAutoConfiguration
      - org.springframework.boot.autoconfigure.websocket.reactive.WebSocketReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration #DB系 使ってない。ORmapperもいらない
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.transaction.TransactionAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jdbc.JdbcRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.aop.AopAutoConfiguration
      - org.springframework.boot.autoconfigure.ssl.SslAutoConfiguration #SSL系 localhostで動くのでいらない
      - org.springframework.boot.autoconfigure.ssl.SslPropertiesAutoConfiguration
  jmx:
    enabled: false
  sql:
    init:
      mode: never
  aop:
    auto: false
    proxy-target-class: false
  data:
    jpa:
      repositories:
        enabled: false