# https://docs.spring.io/spring-boot/appendix/application-properties/index.html#appendix.application-properties.server
server:
  port: 8890
  tomcat:
    keep-alive-timeout: -1 # 無制限
    max-swallow-size: -1  # 無制限
    max-http-form-post-size: 32MB
    connection-timeout: 60s
    threads:
      min-spare: 2
      max: 10
    max-connections: 10
    accept-count: 10
    